UoC_Site/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Net.Http.Headers;
using System.Web.Mvc;
using UoC_Site.Models;

namespace UoC_Site.Controllers
{
    public class CourseController : Controller
    {
        private HttpClient client;
        private List<MediaTypeFormatter> mediaFormatter = new List<MediaTypeFormatter>() { new JsonMediaTypeFormatter() };

        public CourseController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri("http://uoc-api-akee516.azurewebsites.net/");
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        // GET: Course/Details/5
        [HttpGet]
        public async System.Threading.Tasks.Task<ActionResult> Details(int id)
        {
            return View("CourseDetails", await getModel(id));
        }

        // GET: Course/Create
        [HttpGet]
        public ActionResult Create(int studentId)
        {
            return View("CourseCreate", new Course() { Student = new Student() { ID = studentId } } );
        }

        // POST: Course/Create
        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> Create(FormCollection collection)
        {
            try
            {
                Course model = new Course();

                var propertyInfo = model.GetType();

                foreach (var o in collection.AllKeys)
                {
                    try
                    { 
                        propertyInfo.GetProperty(o).SetValue(model, collection[o]);
                    }
                    catch (NullReferenceException)
                    {
                        continue;
                    }
                }

                var response = await client.PostAsJsonAsync("api/Courses?studentId=" + collection["StudentId"], model);
                response.EnsureSuccessStatusCode();

                Uri CourseUrl = response.Headers.Location;

                return RedirectToAction("Overview", "Home");
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Course/Edit/5
        [HttpGet]
        public async System.Threading.Tasks.Task<ActionResult> Edit(int id)
        {
            return View("CourseEdit", await getModel(id));
        }

        // PUT: Course/Edit/5
        [HttpPut]
        public async System.Threading.Tasks.Task<ActionResult> Edit(int id, FormCollection collection)
        {
            try
            {
                Course model = new Course();

                var propertyInfo = model.GetType();

                foreach (var o in collection.AllKeys)
                {
                    try
                    { 
                        propertyInfo.GetProperty(o).SetValue(model, collection[o]);
                    }
                    catch (NullReferenceException)
                    {
                        continue;
                    }
                }

                var response = await client.PutAsJsonAsync("api/Courses/" + id, model);
                response.EnsureSuccessStatusCode();

                Uri CourseUrl = response.Headers.Location;

                return RedirectToAction("Overview", "Home");
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Course/Delete/5
        [HttpGet]
        public async System.Threading.Tasks.Task<ActionResult> Delete(int id)
        {
            return View("CourseDelete", await getModel(id));
        }

        // POST: Course/Delete/5
        [HttpDelete]
        public async System.Threading.Tasks.Task<ActionResult> Delete(int id, FormCollection collection)
        {
            try
            {
                var response = await client.DeleteAsync("api/Courses/" + id);
                response.EnsureSuccessStatusCode();
                Uri CourseUrl = response.Headers.Location;

                return RedirectToAction("Overview", "Home");
            }
            catch
            {
                return View("Error");
            }
        }

        private async System.Threading.Tasks.Task<Course> getModel(int id)
        {
            Course model = null;

            var response = await client.GetAsync("api/Courses/" + id);
            if (response.IsSuccessStatusCode)
            {
                model = await response.Content.ReadAsAsync<Course>(mediaFormatter);
            }

            return model;
        }

        ~CourseController()
        {
            client.Dispose();
        }
    }
}

UoC_Site/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using UoC_Site.Models;

namespace UoC_Site.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public async System.Threading.Tasks.Task<ActionResult> Overview(int id)
        {
            StudentFull model = new StudentFull();
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://uoc-api-akee516.azurewebsites.net/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                // New code:
                var response = await client.GetAsync("api/StudentFulls/" + id);
                if (response.IsSuccessStatusCode)
                {
                    model = await response.Content.ReadAsAsync<StudentFull>(
                        new List<MediaTypeFormatter>() { new JsonMediaTypeFormatter() });
                }

            }

            return View(model);
        }
    }
}

UoC_Site/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Net.Http.Headers;
using System.Web.Mvc;
using UoC_Site.Models;

namespace UoC_Site.Controllers
{
    public class TestController : Controller
    {
        private HttpClient client;
        private List<MediaTypeFormatter> mediaFormatter = new List<MediaTypeFormatter>() { new JsonMediaTypeFormatter() };

        public TestController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri("http://uoc-api-akee516.azurewebsites.net/");
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        // GET: Test/Details/5
        [HttpGet]
        public async System.Threading.Tasks.Task<ActionResult> Details(int id)
        {
            return View("TestDetails", await getModel(id));
        }

        // GET: Test/Create
        [HttpGet]
        public ActionResult Create(int courseId)
        {
            return View("TestCreate", new Test() { Course = new Course() { ID = courseId } });
        }

        // POST: Test/Create
        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> Create(FormCollection collection)
        {
            try
            {
                Test model = new Test();

                var propertyInfo = model.GetType();

                foreach (var o in collection.AllKeys)
                {
                    try
                    { 
                        propertyInfo.GetProperty(o).SetValue(model, collection[o]);
                    }
                    catch (NullReferenceException)
                    {
                        continue;
                    }
                }

                var response = await client.PostAsJsonAsync("api/Tests?courseId=" + collection["CourseId"], model);
                response.EnsureSuccessStatusCode();

                Uri testUrl = response.Headers.Location;

                return RedirectToAction("Overview", "Home");
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Test/Edit/5
        [HttpGet]
        public async System.Threading.Tasks.Task<ActionResult> Edit(int id)
        {
            return View("TestEdit", await getModel(id));
        }

        // PUT: Test/Edit/5
        [HttpPut]
        public async System.Threading.Tasks.Task<ActionResult> Edit(int id, FormCollection collection)
        {
            try
            {
                Test model = new Test();

                var propertyInfo = model.GetType();

                foreach (var o in collection.AllKeys)
                {
                    try
                    {
                        propertyInfo.GetProperty(o).SetValue(model, collection[o]);
                    }
                    catch (NullReferenceException)
                    {
                        continue;
                    }
                }

                var response = await client.PutAsJsonAsync("api/Tests/" + id, model);
                response.EnsureSuccessStatusCode();

                Uri testUrl = response.Headers.Location;

                return RedirectToAction("Overview", "Home");
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Test/Delete/5
        public async System.Threading.Tasks.Task<ActionResult> Delete(int id)
        {
            return View("TestDelete", await getModel(id));
        }

        // DELETE: Test/Delete/5
        [HttpDelete]
        public async System.Threading.Tasks.Task<ActionResult> Delete(int id, FormCollection collection)
        {
            try
            {
                var response = await client.DeleteAsync("api/Tests/" + id);
                response.EnsureSuccessStatusCode();
                Uri testUrl = response.Headers.Location;

                return RedirectToAction("Overview", "Home");
            }
            catch
            {
                return View("Error");
            }
        }

        private async System.Threading.Tasks.Task<Test> getModel(int id)
        {
            Test model = null;

            var response = await client.GetAsync("api/Tests/" + id);
            if (response.IsSuccessStatusCode)
            {
                model = await response.Content.ReadAsAsync<Test>(mediaFormatter);
            }

            return model;
        }

        ~TestController()
        {
            client.Dispose();
        }
    }
}

UoC_Site/Controllers/ToDoItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using UoC_Site.Models;

namespace UoC_Site.Controllers
{
    public class ToDoItemController : Controller
    {
        private HttpClient client;
        private List<MediaTypeFormatter> mediaFormatter = new List<MediaTypeFormatter>() { new JsonMediaTypeFormatter() };

        public ToDoItemController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri("http://uoc-api-akee516.azurewebsites.net/");
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        // GET: ToDoItem/List
        [HttpGet]
        public async System.Threading.Tasks.Task<ActionResult> List(int studentId)
        {
            IEnumerable<ToDoItem> toDoList = null;

            var response = await client.GetAsync("api/ToDoItems?studentId=" + studentId);
            if (response.IsSuccessStatusCode)
            {
                toDoList = await response.Content.ReadAsAsync<IEnumerable<ToDoItem>>(mediaFormatter);
            }

            return View("ToDoItemList", toDoList);
        }

        // GET: ToDoItem/Details/5
        [HttpGet]
        public async System.Threading.Tasks.Task<ActionResult> Details(int id)
        {
            return View("ToDoItemDetails", await getModel(id));
        }

        // GET: ToDoItem/Create
        [HttpGet]
        public ActionResult Create(int studentId)
        {
            return View("ToDoItemCreate", new ToDoItem() { Student = new Student() { ID = studentId } });
        }

        // POST: ToDoItem/Create
        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> Create(FormCollection collection)
        {
            try
            {
                ToDoItem model = new ToDoItem();

                var propertyInfo = model.GetType();

                foreach (var o in collection.AllKeys)
                {
                    try
                    { 
                        propertyInfo.GetProperty(o).SetValue(model, collection[o]);
                    }
                    catch
                    {
                        continue;
                    }
                }

                var response = await client.PostAsJsonAsync("api/ToDoItems?studentId=" + collection["StudentId"], model);
                response.EnsureSuccessStatusCode();

                Uri ToDoItemUrl = response.Headers.Location;

                return RedirectToAction("Overview", "Home", new { id = collection["StudentId"] });
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: ToDoItem/Edit/5
        [HttpGet]
        public async System.Threading.Tasks.Task<ActionResult> Edit(int id)
        {
            var model = await getModel(id);
            model.Student.ID = id;
            return View("ToDoItemEdit", model);
        }

        // PUT: ToDoItem/Edit/5
        [HttpPut]
        public async System.Threading.Tasks.Task<ActionResult> Edit(FormCollection collection)
        {
            try
            {
                ToDoItem model = new ToDoItem();

                var propertyInfo = model.GetType();

                foreach (var o in collection.AllKeys)
                {
                    try
                    {
                        propertyInfo.GetProperty(o).SetValue(model, collection[o]);
                    }
                    catch
                    {
                        continue;
                    }
                }

                var response = await client.PutAsJsonAsync("api/ToDoItems/" + collection["StudentId"], model);
                response.EnsureSuccessStatusCode();

                Uri ToDoItemUrl = response.Headers.Location;

                return RedirectToAction("Overview", "Home");
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: ToDoItem/Delete/5
        [HttpGet]
        public async System.Threading.Tasks.Task<ActionResult> Delete(int id)
        {
            return View("ToDoItemDelete", await getModel(id));
        }

        // DELETE: ToDoItem/Delete/5
        [HttpDelete]
        public async System.Threading.Tasks.Task<ActionResult> Delete(int id, FormCollection collection)
        {
            try
            {
                var response = await client.DeleteAsync("api/ToDoItems/" + id);
                response.EnsureSuccessStatusCode();
                Uri ToDoItemUrl = response.Headers.Location;

                return RedirectToAction("Overview", "Home");
            }
            catch
            {
                return View("Error");
            }
        }

        private async System.Threading.Tasks.Task<ToDoItem> getModel(int id)
        {
            ToDoItem model = null;

            var response = await client.GetAsync("api/ToDoItems/" + id);
            if (response.IsSuccessStatusCode)
            {
                model = await response.Content.ReadAsAsync<ToDoItem>(mediaFormatter);
            }

            return model;
        }

        ~ToDoItemController()
        {
            client.Dispose();
        }

    }
}

UoC_Site/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index: Login";
}

<h2>Select Student:</h2>

<div>
    <ul class="list-inline">
        <li class="list-group">
            <div class="list-group-item">
                <h4 class="list-group-item-heading">Student 1</h4>
                <button class="btn-link">
                    @Html.ActionLink("Login", "Overview", "Home", new { id = 1 }, new { })
                </button>
            </div>
        </li>
        <li class="list-group">
            <div class="list-group-item">
                <h4 class="list-group-item-heading">Student 2</h4>
                <button class="btn-link">
                    @Html.ActionLink("Login", "Overview", "Home", new { id = 2 }, new { })
                </button>
            </div>
        </li>
    </ul>
</div>

UoC_Site/Views/Home/Overview.cshtml
@model UoC_Site.Models.StudentFull

@{
    ViewBag.Title = "Overview";
}

<h2>Overview</h2>

<div>
    <h4>Student</h4>
    <hr />
    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FirstMidName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstMidName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>
        </dl>
    </div>

    <div id="todos">
        <div class="container">
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>
                            <a data-toggle="collapse" href=#todolist>To Do's</a> - @Html.ActionLink("New To Do", "Create", "ToDoItem", new { studentId = Model.ID }, null)
                        </h4>
                    </div>
                    <div id=todolist class="panel-collapse collapse">
                        <div class="panel-body">
                            <p>
                                @Model.ToDoItems.Count ToDo's present.
                                <br />
                                @Html.ActionLink("Veiw Detail List", "List", "ToDoItem", new { studentId = Model.ID }, null)
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="courseHeading">
        <h4>
            Courses - @Html.ActionLink("New Course", "Create", "Course", new { studentId = Model.ID }, null)
        </h4>
    </div>

    <div id="courses">
        @foreach (var c in Model.Courses)
        {
            <div class="container">
                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4>
                                <a data-toggle="collapse" href=#c_@c.ID>@c.Title</a> - @Html.ActionLink("Details", "Details", "Course", new { id = c.ID }, null)
                            </h4>
                        </div>
                        <div id=c_@c.ID class="panel-collapse collapse">
                            <div class="panel-body">
                                <dl class="dl-horizontal">
                                    <dt>Title</dt>
                                    <dd>@c.Title</dd>
                                    <dt>Description</dt>
                                    <dd>@c.Description</dd>
                                </dl>

                                <div id="testsHeading">
                                    <h4>
                                        Tests - @Html.ActionLink("New Test", "Create", "Test", new { courseId = c.ID }, null)
                                    </h4>
                                </div>

                                @foreach (var t in c.Tests)
                                {
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h4>
                                                <a data-toggle="collapse" href=#t_@t.ID>@t.Name</a>
                                                -  @Html.ActionLink("Details", "Details", "Test", new { id = t.ID }, null)
                                            </h4>
                                        </div>
                                        <div id=t_@t.ID class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <dl class="dl-horizontal">
                                                    <dt>Name</dt>
                                                    <dd>@t.Name</dd>
                                                    <dt>Test Date & Time</dt>
                                                    <dd>@t.TestDateTime</dd>
                                                </dl>
                                            </div>
                                        </div>
                                    </div>
                                }

                                <div id="courseHeading">
                                    <h4>
                                        Assignments - @Html.ActionLink("New Assignment", "Create", "Assignment", new { courseId = c.ID }, null)
                                    </h4>
                                </div>

                                @foreach (var a in c.Assignments)
                                {
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h4>
                                                <a data-toggle="collapse" href=#a_@a.ID>@a.Name</a>
                                                -  @Html.ActionLink("Details", "Details", "Assignment", new { id = a.ID }, null)
                                            </h4>
                                        </div>
                                        <div id=a_@a.ID class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <dl class="dl-horizontal">
                                                    <dt>Name</dt>
                                                    <dd>@a.Name</dd>
                                                    <dt>Due Date & Time</dt>
                                                    <dd>@a.DueDateTime</dd>
                                                    <dt>Link To Work</dt>
                                                    <dd><a href=@a.LinkToWork>@a.LinkToWork</a></dd>
                                                </dl>
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>